server.port=9090
spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USERNAME}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
# spring.datasource.url=jdbc:mysql://localhost:3306/videodb
# spring.datasource.username=root
# spring.datasource.password=AnooP@91025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.chat.id=${TELEGRAM_CHAT_ID}

telegram.upload.retry=${TELEGRAM_UPLOAD_RETRY}
google.client-id=${GOOGLE_CLIENT_ID}
jwt.secret=${SECRET}